version: '3.9'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - mailhog
    env_file:
      - ./.env

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none

networks:
  default:
    name: dev
    driver: bridge
